In [1]:
import pandas as pd
from collections import Counter

In [2]:
file = pd.read_csv('data/cnn_data',sep='\t')

In [3]:
file.head()

   class                                           word_seg
0     14  816903 597526 520477 1179558 1033823 758724 63...
1      3  90540 816903 441039 816903 569138 816903 10343...
2     12  816903 1012629 957974 1033823 328210 947200 65...
3     13  563568 1239563 680125 780219 782805 1033823 19...
4     12  816903 816903 816903 139132 816903 312320 1103...

In [4]:
Counter(file['class'])

Counter({1: 5375,
         2: 2901,
         3: 8313,
         4: 3824,
         5: 2369,
         6: 6888,
         7: 3038,
         8: 6972,
         9: 7675,
         10: 4963,
         11: 3571,
         12: 5326,
         13: 7907,
         14: 6740,
         15: 7511,
         16: 3220,
         17: 3094,
         18: 7066,
         19: 5524})

In [5]:
file = file.sample(frac=1).reset_index(drop=True)

In [6]:
file.head()

   class                                           word_seg
0      2  1089809 995196 396945 730089 244780 437916 126...
1     15  585102 1097342 520477 491804 460600 738281 111...
2      3  54111 281403 412680 250930 726082 422098 10338...
3      8  816903 1141528 610495 1226448 693588 693019 10...
4      9  20185 637864 1057544 395708 361815 816903 5019...

In [7]:
fenge = [0.8,0.1,0.1]

In [8]:
file.iloc[0:int(len(file)*fenge[0]),].to_csv('data/train_data',index=0,header=0,sep='\t')
file.iloc[int(len(file)*fenge[0]):int(len(file)*(fenge[0]+fenge[1])),].to_csv('data/val_data',index=0,header=0,sep='\t')
file.iloc[int(len(file)*(fenge[0]+fenge[1])):len(file),].to_csv('data/test_data',index=0,header=0,sep='\t')

In [9]:
range(int(len(file)*(fenge[0]+fenge[1])),len(file))

range(92049, 102277)

In [10]:
pd.read_csv('data/val_data',header=None)

                                                       0
0      15\t1093451 54111 250930 111874 125402 1033823...
1      9\t696569 1004569 520477 1002400 140531 424348...
2      9\t232957 816903 716866 460600 806785 747560 5...
3      1\t588341 460600 831504 1033823 883131 752575 ...
4      14\t599826 280818 666749 681443 816903 907959 ...
5      8\t138047 520477 403305 766772 552461 816903 9...
6      4\t769051 1226448 129169 806280 876555 1150366...
7      8\t1173639 54885 1171209 118752 701146 816903 ...
8      3\t266069 1226448 949070 119159 816903 816903 ...
9      6\t340401 966562 426716 479552 520477 909264 1...
10     3\t148697 426409 1033823 1110352 892940 66495 ...
11     16\t693588 887156 533560 22666 816903 266069 1...
12     19\t108204 1226448 910091 54111 81420 325497 9...
13     9\t816903 825744 447420 477703 930754 1163183 ...
14     17\t545370 94560 520477 859339 787329 292622 1...
15     7\t1238617 631173 1078737 358187 315535 333764...
16     8\t677157 7166 1244545 653104 416085 520477 38...
17     14\t816903 57231 1226448 745041 816903 339959 ...
18     15\t661629 520477 61571 100382 157586 1203094 ...
19     1\t816903 266069 1226448 92345 524900 816903 7...
20     2\t240275 816903 554251 816903 815943 479552 1...
21     15\t1244596 61660 777331 558281 879848 273994 ...
22     13\t244037 632718 1122693 1080587 663450 61647...
23     9\t115261 847972 663669 13193 520477 357152 64...
24     1\t655201 178725 66758 825506 806803 105283 81...
25     18\t951577 257985 477703 193655 520477 87439 2...
26     12\t1098157 1121268 184574 242461 1136318 1074...
27     2\t57932 1033823 563568 1057544 234165 905055 ...
28     15\t1018377 1257015 966562 299458 520477 41431...
29     16\t1073373 1111619 816903 674882 211511 10338...
...                                                  ...
10198  19\t67633 288357 800742 23439 890865 638334 81...
10199  15\t686820 184574 882965 1033823 673863 445187...
10200  6\t3849 36066 349848 1049092 74725 64132 10338...
10201  11\t209541 968366 1207796 448557 844369 639546...
10202  13\t386754 553856 669476 616471 389613 526298 ...
10203  13\t386754 553856 512983 751895 279469 515268 ...
10204  18\t816903 11746 1033823 39301 411707 352476 5...
10205  2\t816903 282208 20700 816903 837665 101439 35...
10206  4\t266169 432219 1033823 600366 132364 708286 ...
10207  13\t816903 1222068 266784 788510 307880 840387...
10208  13\t1178538 942575 810179 816903 1178538 60961...
10209  4\t1211274 1207796 57692 520477 766772 1033823...
10210  9\t816903 1122814 611601 94555 816903 1224594 ...
10211  12\t816903 816903 816903 816903 816903 816903 ...
10212  17\t295014 520477 460600 695445 659374 325497 ...
10213  5\t1068182 229783 816903 1212070 301026 816903...
10214  19\t796858 460600 874987 1033823 1197924 83378...
10215  15\t402361 742240 806755 366191 539278 300780 ...
10216  7\t100078 41607 680478 1033823 694511 816903 6...
10217  6\t134782 1226448 572782 490535 1081563 918835...
10218  6\t585102 930754 18911 548150 627785 1033823 6...
10219  6\t61609 457828 552622 830766 969091 520477 49...
10220  10\t900002 224294 834740 278629 1025743 119530...
10221  18\t179319 460600 1014719 1033823 411707 28346...
10222  5\t545370 94560 520477 1150820 1033823 674551 ...
10223  14\t816903 816903 816903 816903 816903 816903 ...
10224  3\t1186228 36689 105283 421960 669201 105283 8...
10225  16\t1137386 88101 1226448 1114843 89613 816903...
10226  13\t1159540 1270052 520477 789842 477703 93075...
10227  1\t626900 572782 536077 323159 257985 482085 8...

[10228 rows x 1 columns]

In [11]:
pd.read_csv('data/train_data',header=None)

                                                       0
0      2\t1089809 995196 396945 730089 244780 437916 ...
1      15\t585102 1097342 520477 491804 460600 738281...
2      3\t54111 281403 412680 250930 726082 422098 10...
3      8\t816903 1141528 610495 1226448 693588 693019...
4      9\t20185 637864 1057544 395708 361815 816903 5...
5      14\t545370 678048 37356 518787 534086 499112 5...
6      11\t411707 433509 520477 655201 131604 404543 ...
7      15\t816903 1191594 61571 258218 138140 1230376...
8      3\t816903 927878 553856 520477 426409 30306 26...
9      11\t1115586 816903 816903 937688 1198219 72840...
10     15\t54111 941047 77036 965936 593316 300241 76...
11     3\t335922 260177 358425 589909 48492 791685 74...
12     4\t816903 970296 1226448 726178 1033823 749188...
13     7\t665901 1025743 461154 990423 520477 132419 ...
14     3\t816903 816903 816903 816903 816903 816903 8...
15     11\t816903 816903 426716 1115586 816903 122608...
16     15\t1225392 787112 317467 920327 67522 920327 ...
17     8\t821270 787993 625781 340401 966562 1257015 ...
18     12\t545370 766772 875888 1244312 7823 483164 2...
19     17\t816903 821270 572782 603408 830802 323159 ...
20     8\t138531 1204906 460600 18391 442922 138531 1...
21     19\t816903 816903 598948 1099608 1134471 99536...
22     10\t816903 816903 1062522 686860 964250 920327...
23     8\t386754 553856 666666 520477 1048411 518915 ...
24     7\t824446 816903 816903 821397 146335 1231567 ...
25     14\t816903 490535 312698 756428 626786 38841 7...
26     1\t152341 330782 1054308 1008006 816903 848000...
27     19\t816903 398177 792991 1128683 929897 479552...
28     3\t287730 1033823 319243 460600 30314 1251322 ...
29     3\t312181 1038656 460983 1242010 177456 485807...
...                                                  ...
81791  19\t462508 752874 599317 490535 101879 520477 ...
81792  2\t1154217 541734 520477 608869 1269852 825039...
81793  18\t837521 553856 102711 966562 490374 893240 ...
81794  8\t816903 386754 553856 1257015 966562 1054308...
81795  19\t816903 816903 701424 323372 1267049 520477...
81796  3\t171409 1033823 38117 460600 775614 1097342 ...
81797  9\t911823 611601 1224594 153705 816903 1216280...
81798  3\t61571 100078 477703 54111 240644 930754 747...
81799  12\t782716 833235 440061 520477 1213632 520477...
81800  8\t138047 520477 526319 386932 876555 572744 1...
81801  7\t816903 585102 926111 325497 1033823 892167 ...
81802  13\t426716 1115586 1019695 1162056 526298 1772...
81803  8\t816903 309047 1073840 587327 490535 94449 6...
81804  6\t347900 605692 340401 966562 520355 599826 5...
81805  13\t426716 920327 778803 215605 705557 816903 ...
81806  3\t132454 820884 381752 449130 520477 681139 4...
81807  4\t937273 330478 520477 98267 961536 399962 75...
81808  18\t1071658 265734 876555 323414 553856 107145...
81809  2\t1031246 1000483 834740 816903 411707 35579 ...
81810  14\t713316 1204054 1033823 1260243 816903 4049...
81811  12\t816903 816903 1151396 966562 1062760 59982...
81812  4\t197355 1097851 340401 966562 520355 1077659...
81813  13\t301918 812370 816903 1025743 38859 1151786...
81814  9\t6333 816903 727721 764656 1033823 1091317 9...
81815  18\t119103 666655 741035 102499 261090 874391 ...
81816  11\t1182011 449130 520477 177456 540055 930754...
81817  7\t1232735 520477 1194630 490535 655201 610495...
81818  19\t816903 400027 1134038 582851 1033823 61286...
81819  14\t171303 383790 520477 756628 520477 429628 ...
81820  12\t477891 414956 490735 458209 930754 460600 ...

[81821 rows x 1 columns]